blank_issues_enabled: false
contact_links:
  - name: Question or usage help
    url: https://github.com/goddivor/seticon-cli/discussions
    about: Ask questions and get help with using seticon-cli.
  - name: npm package
    url: https://www.npmjs.com/package/seticon-cli
    about: View the published package on npm.
